org.gradle.parallel=true
org.gradle.caching=true
org.gradle.vfs.watch=false
org.gradle.configuration-cache=true

org.gradle.jvmargs="-Xmx4G"

group=gg.pufferfish.pufferfish
mcVersion=26.1.2
apiVersion=26.1.2
channel=STABLE
paperRef=70eaed653d2260e42e510ea16e8fcb50152aa5ef
paperweight.defaultMinFuzz=0.1
